/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telaTeste1;

import javax.swing.JFrame;

/**
 *
 * @author jvale
 */
public class Comanda extends javax.swing.JFrame {

    private int idMesa;
    private double subtotal;

   
    public Comanda(int idMesa, double subtotal) {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        this.idMesa = idMesa;
        this.subtotal = subtotal;

        // Atualiza os campos de texto com as informações recebidas
        idMesaTextField7.setText("" + idMesa);
        totalTextField6.setText("Subtotal: R$ " + subtotal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pagamentoComanda = new javax.swing.JButton();
        voltarComanda = new javax.swing.JButton();
        totalTextField6 = new javax.swing.JTextField();
        idMesaTextField7 = new javax.swing.JTextField();
        IdMESA1 = new javax.swing.JLabel();
        TOTAL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));

        jPanel2.setBackground(new java.awt.Color(51, 0, 0));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("COMANDA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pagamentoComanda.setBackground(new java.awt.Color(51, 0, 0));
        pagamentoComanda.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        pagamentoComanda.setForeground(new java.awt.Color(255, 204, 0));
        pagamentoComanda.setText("PAGAMENTO");
        pagamentoComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagamentoComandaActionPerformed(evt);
            }
        });

        voltarComanda.setBackground(new java.awt.Color(51, 0, 0));
        voltarComanda.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        voltarComanda.setForeground(new java.awt.Color(255, 204, 0));
        voltarComanda.setText("VOLTAR");
        voltarComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarComandaActionPerformed(evt);
            }
        });

        totalTextField6.setBackground(new java.awt.Color(51, 0, 0));
        totalTextField6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        totalTextField6.setForeground(new java.awt.Color(255, 204, 0));
        totalTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalTextField6ActionPerformed(evt);
            }
        });

        idMesaTextField7.setBackground(new java.awt.Color(51, 0, 0));
        idMesaTextField7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        idMesaTextField7.setForeground(new java.awt.Color(255, 204, 0));
        idMesaTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idMesaTextField7ActionPerformed(evt);
            }
        });

        IdMESA1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        IdMESA1.setForeground(new java.awt.Color(51, 0, 0));
        IdMESA1.setText("MESA:");

        TOTAL.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        TOTAL.setForeground(new java.awt.Color(51, 0, 0));
        TOTAL.setText("TOTAL:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IdMESA1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idMesaTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(pagamentoComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133)
                        .addComponent(voltarComanda)))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdMESA1)
                    .addComponent(idMesaTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TOTAL))
                .addGap(170, 170, 170)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voltarComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pagamentoComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pagamentoComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagamentoComandaActionPerformed
           new Pagamento(idMesa, subtotal).setVisible(true);

    }//GEN-LAST:event_pagamentoComandaActionPerformed

    private void voltarComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarComandaActionPerformed
        dispose();
    }//GEN-LAST:event_voltarComandaActionPerformed

    private void totalTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalTextField6ActionPerformed

    private void idMesaTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idMesaTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idMesaTextField7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Comanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Comanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Comanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Comanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                int idMesa = 1; // Replace with actual idMesa value
                double subtotal = 50.0;
                new Comanda(idMesa, subtotal).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IdMESA1;
    private javax.swing.JLabel TOTAL;
    private javax.swing.JTextField idMesaTextField7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton pagamentoComanda;
    private javax.swing.JTextField totalTextField6;
    private javax.swing.JButton voltarComanda;
    // End of variables declaration//GEN-END:variables
}
